### ISSUE TITLE
Close server after tests

### ISSUE THREAD

**Issue by ghost** [forwardemail/supertest#437]
I have koa server with mongo connection, jest as test framework.

```
const app = new Koa()
...
export default app.listen(PORT, (err) => {
  if (err) console.log(err)

  if (!IS_TEST) {
    console.log(`Server running on port: ${PORT}`)
  }
})
```

After success finish test or fail server connection steel works, how close koa server connection after test ?

Test example:
```
import supertest from 'supertest'
import mongoose from 'mongoose'
import server from '../../../app/server'
import User from '../../../app/models/user'

const r = supertest.agent(server.listen())

afterEach(async (done) => {
  await mongoose.connection.db.dropDatabase()
  done()
})

describe('Authorization', () => {
  describe('POST /signup', () => {
    const userData = {
      email: 'test@test.com',
      password: 111111,
    }

    test('success create user', (done) => {
      r
        .post(`/api/auth/signup`)
        .send(userData)
        .expect(200)
        .expect({
          data: {
            email: userData.email,
          },
        })
        .end(done)
    })

    test('fail of user create, password required', (done) => {
      const userData = {
        email: 'test@test.com',
      }

      r
        .post(`/api/auth/signup`)
        .send(userData)
        .expect(400)
        .expect({
          errors: {
            password: 'Password required',
          },
        })
        .end(done)
    })

    test('fail of user create, user already exist', async (done) => {
      const userData = {
        email: 'test@test.com',
        password: 111111,
      }

      await User.create(userData)

      r
        .post(`/api/auth/signup`)
        .send(userData)
        .expect(400)
        .expect({
          errors: {
            email: `User already exist`,
          },
        })
        .end(done)
    })
  })
})
```

**Comment by atomantic** [comment]
same problem with express and the latest version of mocha (only with the latest mocha)--the tests never exit because the server never shuts down.

**Comment by devpascoe** [comment]
Thanks @atomantic if i roll back to 3.5.3 i'm all good.
```
"mocha": "~3.5.3", 
```

**Comment by FuzzOli87** [comment]
Running into the same issue here. A connection to a kafka cluster remains alive after tests are done so it never shuts down.

**Comment by JakubSimandl** [comment]
This might be cause by https://github.com/visionmedia/supertest/issues/430. If you are calling `done()` in the .end() callback.

**Comment by DamianLion** [comment]
seems to be an issue with mocha@4.0.1

**Comment by demisx** [comment]
Have you tried `mocha --exit`?

**Comment by michaelBenin** [comment]
app.listen returns a server instance you need to tear down as the lest test.

also yes newest mocha --exit has changed: https://github.com/visionmedia/supertest/issues/437

**Comment by devpascoe** [comment]
hate to ask @michaelBenin but do you have a sample on this tear down code block?

**Comment by devpascoe** [comment]
never mind, thanks to @demisx and the release notes of mocha 4 this now functions as before with the --exit flag

#2879: By default, Mocha will no longer force the process to exit once all tests complete. This means any test code (or code under test) which would normally prevent node from exiting will do so when run in Mocha. Supply the --exit flag to revert to pre-v4.0.0 behavior 
https://github.com/mochajs/mocha/issues/2879

**Comment by deployable** [comment]
I use the following to setup and tear down the server in mocha 4+
```
const supertest = require('supertest')
const app = require('../../app')

describe('int::app', function(){

  let request = null
  let server = null

  before(function(done){
    server = app.listen(done)
    request = supertest.agent(server)
  })

  after(function(done){
    server.close(done)
  })

  it('should get /api/v1/laps/85299', function(){
    return request.get('/api/v1/laps/85299')
      .expect(200, { data: {} })
  })

})
```

**Comment by timeemit** [comment]
@deployable That works for me but it can take a few seconds for a larger suite to teardown.  I'm guessing that it's because supertest is keeping `keep-alive` connections around?  Does anyone have an idea how to force their closure?

**Comment by deployable** [comment]
@timeemit I've run into that outside of tests. There are some modules that add connection tracking and can close sockets from that, I'm struggling to recall/find names though. 

I think some old old versions of node had bugs where new connections could actually keep the tcp server up too.

**Comment by jakubrpawlowski** [comment]
I just run into the same issue running tape with supertest.agent(app). Tape is waiting for the server to close. I will let you know as soon as I find a solution.

**Comment by deployable** [comment]
@jakubrpawlowski https://github.com/isaacs/server-destroy

**Comment by jakubrpawlowski** [comment]
Unfortunately even after using both **server-destroy** and **http-shutdown** and afterwards waiting for keep-alive to finish the server is still available for more tests (I can still call agent 5 minutes after server should have been shut down and still get reference to the same server and 200 status code back).

**Comment by jakubrpawlowski** [comment]
Okay I figured it out finally. It was Mongoose that was causing the issue in my case. After requiring it in the test file and calling `mongoose.connection.close()` in the very last test everything seems to be working fine! Wow I can't believe this took me almost 8 hours!

**Comment by robertdumitrescu** [comment]
If with mocha 3.5.3 everything works smoothly, should we really encourage developers that are using supertest to add some teardown hacks just to make supertest compatible with the new mocha version or should we aim to fix supertest to work properly again?

Probably the second option right? Just sayin'

**Comment by mleanos** [comment]
> Okay I figured it out finally. It was Mongoose that was causing the issue in my case.

Same here! I was closing closing my http server, but wasn't closing my Mongoose connection.

Thanks for the hint @jakubrpawlowski!

**Comment by BrianHVB** [comment]
> Okay I figured it out finally. It was Mongoose that was causing the issue in my case.

For me it was PostgreSQL, but the same thing. Also, after I closed my database connection within `after()`, I refactored my test setup back to the original as outlined in the Supertest documentation. (Calling `app.get(...).expect(...)` directly) instead of the structure mentioned by @deployable and it works. As soon as Mocha finishes, the application exits.

**Comment by deployable** [comment]
It looks like supertest [sets up a new server](https://github.com/visionmedia/supertest/blob/199506d8dbfe0bb1434fc07c38cdcd1ab4c7c926/index.js#L19-L20) for every call to `request()`. That server will close when you [call `.end()`](https://github.com/visionmedia/supertest/blob/199506d8dbfe0bb1434fc07c38cdcd1ab4c7c926/lib/test.js#L120-L126).  

Possibly test's that don't use `end()` are leaving the server (and mocha) running?

**Comment by mikelax** [comment]
I have upgraded the dev dependency for mocha to be the latest, 5.x. 
I added the `--exit` to the `npm test` command, otherwise it has the same issue where mocha doesn't exit after the tests have finished. The issue in with how the test setups are done, all servers that are open aren't closed. 

PRs welcome to fix this. A first step might be to break the single monolithic test file into smaller, more manageable test files.

**Comment by developer239** [comment]
Is this fixed? 😅

**Comment by marlomgirardi** [comment]
In my case, the issue was in the Winston logger, because `exitOnError` was`false`.

So basically, I had 2 options...

1. Change `exitOnError` to `true`
2. Use `--exit` in mocha config

The best option, in my opinion, was use the `--exit`.

**Comment by kepikoi** [comment]
Unfortunately express still doesn't exit on calling .end(). This is reproducible with a basic setup:

package.json:
```
{
  "name": "tape-express",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "tape index.spec.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.16.3",
    "supertest": "^3.3.0",
    "tape": "^4.9.1"
  }
}
```

index.js:
```
const
    app = require("express")()
    , port = process.env.PORT || 3301
;

app.set("port", port);

app.get("/test", (req, res, next) => {
    return res.status(200).send("test");
});

app.listen(port, console.log.bind(this, `listening on port ${port}`));

module.exports = app;
```

index.spec.js:
```
const
    test = require("tape")
    , supertest = require("supertest")
    , app = require("./index")
;

test("/test should reply with 200", t => {
    supertest(app)
        .get("/test")
        .expect(200)
        .end((err,res) => {
            if(err){
                return t.fail(err)
            }
            t.pass("/test replied with 200");
            t.end()
        })
    ;

    setTimeout(()=>{
        t.fail("failed to shut down express");
        process.exit(1);
    },30000)

});
```

execute test
````PS C:\www\testing\tape-express> npm test

> tape-express@1.0.0 test C:\www\testing\tape-express
> tape index.spec.js

listening on port 3301
TAP version 13
# /test should reply with 200
ok 1 /test replied with 200
not ok 2 failed to shut down express
  ---
    operator: fail
    at: Timeout.setTimeout [as _onTimeout] (C:\www\testing\tape-express\index.spec.js:21:11)
    stack: |-
      Error: failed to shut down express
          at Test.assert [as _assert] (C:\www\testing\tape-express\node_modules\tape\lib\test.js:224:54)
          at Test.bound [as _assert] (C:\www\testing\tape-express\node_modules\tape\lib\test.js:76:32)
          at Test.fail (C:\www\testing\tape-express\node_modules\tape\lib\test.js:317:10)
          at Test.bound [as fail] (C:\www\testing\tape-express\node_modules\tape\lib\test.js:76:32)
          at Timeout.setTimeout [as _onTimeout] (C:\www\testing\tape-express\index.spec.js:21:11)
          at ontimeout (timers.js:424:11)
          at tryOnTimeout (timers.js:288:5)
          at listOnTimeout (timers.js:251:5)
          at Timer.processTimers (timers.js:211:10)
  ...
npm ERR! Test failed.  See above for more details.
````
I added the repro here: https://github.com/kepikoi/supertest-issue-430

**Comment by bwegrzyn** [comment]
I'm seeing this issue too. No matter what I do, I'm unable to get Jest to exit cleanly after making a call with supertest. If I remove the supertest call, it exists cleanly as expected.

**Comment by Ohadbasan** [comment]
This pr resolved this issue for me.
#522

**Comment by marcospgp** [comment]
> Unfortunately express still doesn't exit on calling .end(). This is reproducible with a basic setup:
> 
> package.json:
> 
> ```
> {
>   "name": "tape-express",
>   "version": "1.0.0",
>   "description": "",
>   "main": "index.js",
>   "scripts": {
>     "test": "tape index.spec.js"
>   },
>   "keywords": [],
>   "author": "",
>   "license": "ISC",
>   "dependencies": {
>     "express": "^4.16.3",
>     "supertest": "^3.3.0",
>     "tape": "^4.9.1"
>   }
> }
> ```
> index.js:
> 
> ```
> const
>     app = require("express")()
>     , port = process.env.PORT || 3301
> ;
> 
> app.set("port", port);
> 
> app.get("/test", (req, res, next) => {
>     return res.status(200).send("test");
> });
> 
> app.listen(port, console.log.bind(this, `listening on port ${port}`));
> 
> module.exports = app;
> ```
> index.spec.js:
> 
> ```
> const
>     test = require("tape")
>     , supertest = require("supertest")
>     , app = require("./index")
> ;
> 
> test("/test should reply with 200", t => {
>     supertest(app)
>         .get("/test")
>         .expect(200)
>         .end((err,res) => {
>             if(err){
>                 return t.fail(err)
>             }
>             t.pass("/test replied with 200");
>             t.end()
>         })
>     ;
> 
>     setTimeout(()=>{
>         t.fail("failed to shut down express");
>         process.exit(1);
>     },30000)
> 
> });
> ```
> execute test
> 
> ```postscript
> > tape-express@1.0.0 test C:\www\testing\tape-express
> > tape index.spec.js
> 
> listening on port 3301
> TAP version 13
> # /test should reply with 200
> ok 1 /test replied with 200
> not ok 2 failed to shut down express
>   ---
>     operator: fail
>     at: Timeout.setTimeout [as _onTimeout] (C:\www\testing\tape-express\index.spec.js:21:11)
>     stack: |-
>       Error: failed to shut down express
>           at Test.assert [as _assert] (C:\www\testing\tape-express\node_modules\tape\lib\test.js:224:54)
>           at Test.bound [as _assert] (C:\www\testing\tape-express\node_modules\tape\lib\test.js:76:32)
>           at Test.fail (C:\www\testing\tape-express\node_modules\tape\lib\test.js:317:10)
>           at Test.bound [as fail] (C:\www\testing\tape-express\node_modules\tape\lib\test.js:76:32)
>           at Timeout.setTimeout [as _onTimeout] (C:\www\testing\tape-express\index.spec.js:21:11)
>           at ontimeout (timers.js:424:11)
>           at tryOnTimeout (timers.js:288:5)
>           at listOnTimeout (timers.js:251:5)
>           at Timer.processTimers (timers.js:211:10)
>   ...
> npm ERR! Test failed.  See above for more details.
> ```
> 
> I added the repro here: https://github.com/kepikoi/supertest-issue-430

The problem might be the module.exports exporting the express app itself instead of the result of app.listen()

**Comment by codebling** [comment]
> The problem might be the module.exports exporting the express app itself instead of the result of app.listen()

This doesn't help. `Server.listen()` returns the `Server` ([here's the code](https://github.com/nodejs/node/blob/v11.14.0/lib/net.js#L1398))

**Comment by pablolopesk8** [comment]
> Okay I figured it out finally. It was Mongoose that was causing the issue in my case. After requiring it in the test file and calling `mongoose.connection.close()` in the very last test everything seems to be working fine! Wow I can't believe this took me almost 8 hours!
> 
> ```
> test('teardown', t => {
>     app.close()
>     mongoose.connection.close()
>     t.end() 
> })
> ```

This works for me! Close a server manually when the tests ended seems to me a good approach! Thanks @jakubrpawlowski

**Comment by marcospgp** [comment]
It's sad how much developer time these things waste for very little benefit. You guys should just let these things timeout, or force them to shut down. There's no value in getting this to work perfectly when it doesn't out of the box.

**Comment by jjangga0214** [comment]
When using **koa** (v2.7.0), this issue could be resolved by replacing app.listen() to app.callback().
For example,

```js
const supertest = require('supertest')
const { app } = require('../src/app')

const request = supertest(app.callback())

describe('routes', () => {
  it(' GET /', () => {
    return request.get('/').expect(200)
  })
})
```

**Comment by meelash** [comment]
> It's sad how much developer time these things waste for very little benefit. You guys should just let these things timeout, or force them to shut down. There's no value in getting this to work perfectly when it doesn't out of the box.

In some cases, if the server is not shutting down it's because of database, ftp, etc. connections remaining open, not in the test, but in the actual code; so there is some benefit in tracking down where that is and cleaning them up correctly. I imagine there is some harm in having hundreds or thousands of connections sitting around open when you push to production and every request is opening a new one, for example.

**Comment by remcohaszing** [comment]
I have created an Axios based alternative that doesn’t suffer from this issue.

https://www.npmjs.com/package/axios-test-instance

**Comment by ldeveloperl1985** [comment]
```

**Comment by kdhttps** [comment]
`app.close(done)` works for me.

```
// index.js

const app = express();
const server = require('http').Server(app);
.
.
.
server.listen(3000, () => {
});

module.exports = server;

```

```
// test.js

const request = require('supertest');
const app = require('../index');

describe('Module', () => {
  after(function (done) {
    app.close(done)
  })

  it('Health Check', (done) => {
    request(app)
      .get('/health-check')
      .expect(200)
      .end((err, res) => {
        if (err) throw done(err);

        done();
      });
  });
});
```

**Comment by developer239** [comment]
⬆️  I know this is going to be unpopular opinion but I would rather use `async/await` and force quit the tests at the end. Come on, it is 2020.

**Comment by vccolombo** [comment]
@kdhttps answer works for me. Be aware that [you need to export the listen result, not the app itself](https://stackoverflow.com/questions/14515954/how-to-properly-close-node-express-server).
In my case I was using app.listen() directly to start the server, so I did:

```javascript
const server = app.listen(3000);
module.exports = server;
```

**Comment by AaronGoldsmith1** [comment]
calling `process.exit()`in my final test worked for me

**Comment by ChrisChiasson** [comment]
> call `.end()`

I have found that the server does not close when end is called. I have my suspicions as to why.

**Comment by ChrisChiasson** [comment]
> It looks like supertest [sets up a new server](https://github.com/visionmedia/supertest/blob/199506d8dbfe0bb1434fc07c38cdcd1ab4c7c926/index.js#L19-L20) for every call to `request()`. That server will close when you [call `.end()`](https://github.com/visionmedia/supertest/blob/199506d8dbfe0bb1434fc07c38cdcd1ab4c7c926/lib/test.js#L120-L126).
> 
> Possibly test's that don't use `end()` are leaving the server (and mocha) running?

@deployable I have found that the server does not close when end is called. It appears to be waiting for the underlying Request's end to be called, which never happens.

**Comment by TiMESPLiNTER** [comment]
For me the problem was, that I started several timers using `setTimeout()` or `setInterval()`. Those keep the process alive. After I appended to all `setTimeout()` and `setInterval()` calls a `.unref()` supertest was able to properly shut down the process and jest didn't report the error: 

> A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
