### ISSUE TITLE
 TypeError: Cannot read property 'formatters' of undefined

### ISSUE THREAD

**Issue by fabioformosa** [forwardemail/supertest#582]
I get the following error message
```
 FAIL  tests/index.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'formatters' of undefined

      at Object.<anonymous> (node_modules/supertest/node_modules/debug/src/node.js:156:33)
      at Object.<anonymous> (node_modules/supertest/node_modules/debug/src/index.js:10:20)
```
The excerpt of the package.json
```
"devDependencies": {
    "@types/chai": "^4.1.7",
    "@types/express": "4.16.1",
    "@types/jest": "^24.0.15",
    "@types/node": "10.10.3",
    "@types/supertest": "^2.0.7",
    "@typescript-eslint/parser": "1.5.0",
    "chai": "4.2.0",
    "cross-env": "^5.2.0",
    "jest": "^24.5.0",
    "supertest": "^4.0.2",
    "ts-jest": "^24.0.2",
    "ts-node": "8.0.3",
    "typescript": "3.3.4000",
    "typescript-eslint-parser": "22.0.0"
  },
```
any help?

**Comment by jonathansamines** [comment]
@fabioformosa Can you provide a complete reproduction example to take a look at?

**Comment by fabioformosa** [comment]
I have some extra details.
I mocked a module lib (saved in package.json) putting the mock into `__mocks__` folder and enabling jest `automock: true` property.

I get the error with this jest config:

> module.exports = {
 preset: 'ts-jest',
 testEnvironment: 'node',
 automock: true
};

Instead, no error with:

> module.exports = {
 preset: 'ts-jest',
 testEnvironment: 'node',
 automock: true,
 unmockedModulePathPatterns: [],
};
