### ISSUE TITLE
[windows, post request] error: password authentication failed for user

### ISSUE THREAD

**Issue by lybrus** [forwardemail/supertest#598]
Hi,

Post request doesn't work on my local machine (it seems, trying to auth with windows user), but works fine with travis-ci. Get requests work fine. If I send post request manually - it works fine.

Test:
```javascript
import server from '~/app'
import request from 'supertest'

describe('Order creation', () => {
    test('Create order', async () => {
        const response = await request(server)
            .post('/api/v1/orders/')
            .send({
                kit: 'M',
                deliveryMethod: 'pickup',
                address: '433111, Russia, Moscow, 5-1-34',
                name: 'Ivan',
                phone: '+7 (916) 123-34-54'
            })
            .set('Content-type', 'application/json')
            .expect('Content-Type', /json/)
            .expect(200)

        expect(Object.keys(response.body)).toContain('orderId')
    })
})

afterEach(() => {
  server.close()
})
```

Error:
```console
 FAIL  source/api/v1/orders/createOrder.test.js (5.602s)
  ● Console

    console.log node_modules/koa-logger/index.js:52
        <-- POST /api/v1/orders/
    console.log node_modules/koa-logger/index.js:52
        xxx POST /api/v1/orders/ 500 141ms -
    console.error node_modules/koa/lib/application.js:189
      undefined
    console.error node_modules/koa/lib/application.js:190
        error: password authentication failed for user "[WINDOWS_USERNAME]"
            at Connection.Object.<anonymous>.Connection.parseE (C:\projects\bee-ble\bee-
ble-app-backend\node_modules\pg\lib\connection.js:601:11)
            at Connection.Object.<anonymous>.Connection.parseMessage (C:\projects\bee-bl
e\bee-ble-app-backend\node_modules\pg\lib\connection.js:398:19)
            at Socket.<anonymous> (C:\projects\bee-ble\bee-ble-app-backend\node_modules\
pg\lib\connection.js:120:22)
            at Socket.emit (events.js:203:13)
            at addChunk (_stream_readable.js:295:12)
            at readableAddChunk (_stream_readable.js:276:11)
            at Socket.Readable.push (_stream_readable.js:210:10)
            at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
    console.error node_modules/koa/lib/application.js:191
      undefined

  ● Order creations › Create order should add records to tables orders and accounts

    expected 200 "OK", got 500 "Internal Server Error"



      at Test.Object.<anonymous>.Test._assertFunction (node_modules/supertest/lib/test.j
s:283:11)
      at Test.Object.<anonymous>.Test.assert (node_modules/supertest/lib/test.js:173:18)
      at localAssert (node_modules/supertest/lib/test.js:131:12)
      at node_modules/supertest/lib/test.js:128:5
      at Test.Object.<anonymous>.Request.callback (node_modules/superagent/lib/node/inde
x.js:728:3)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:916:18)
```

**Comment by jonathansamines** [comment]
@lybrus Can you put together an isolated reproduction I can locally check?
