### ISSUE TITLE
Add async/await examples to documentation

### ISSUE THREAD

**Issue by JeremyLoy** [forwardemail/supertest#659]
I didn't realize until after using this library for a few days that `supertest.Test` (the return value for `.get`, `.expect` etc) extends `Promise<Response>` after a few generations of inheritance.

This means that you can do the following:
```js
import request from 'supertest'
const response = await request.get('/').expect(200)
```

One key thing to note is that `.end` should NOT be called when using `async/await`

**Comment by alexanderankin** [comment]
hey how did you wire this up with the app object itself? i keep getting errors? based on the README it seems like it should be done like so:

```
var request = require('supertest')
var express = require('express')
var { expect } = require('chai')
(async () => { var response = await request(express()).get('/'); expect(response.statusCode).to.equal(404); })();
```

**Comment by adrianwix** [comment]
Something like this make jest complains.
```js
describe('/iam/users (GET)', () => {
        test('Return 403 if the user is not authenticated', async () => {
            expect.assertions(1)
            const response = await request(server)
                .get('/iam/users')
                .set('x-tenant', '1')

            expect(response.status).toBe(404)
        })
    })
```

```bash
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TCPSERVERWRAP

      37 |             expect.assertions(1)
      38 |             const response = await request(server)
    > 39 |                 .get('/iam/users')
         |                  ^
      40 |                 .set('x-tenant', '1')
      41 | 
      42 |             expect(response.status).toBe(404)

      at Test.Object.<anonymous>.Test.serverAddress (node_modules/supertest/lib/test.js:59:33)
      at new Test (node_modules/supertest/lib/test.js:36:12)
      at Object.obj.<computed> [as get] (node_modules/supertest/index.js:25:14)
      at Object.<anonymous> (test/user.e2e-spec.ts:39:18)
```

**Comment by tgiardina** [comment]
This is a pretty big problem! A lot of people use Jest with SuperTest. But currently Jest's `--detectOpenHandles` doesn't work for a big chunk of its users (see [here](https://github.com/facebook/jest/issues/9473)). So I'm stuck with the dreaded `Jest did not exit one second after the test run has completed` and no error logging and no documentation.
`

**Comment by jtomaszewski** [comment]
> https://github.com/visionmedia/supertest/issues/659#issuecomment-719601457

This is not because you're asing async/await, it's because you're not closing server after test finishes.

Do it like that:

```ts

let server: Server;
beforeEach(() => {
  server = app.listen();
});
afterEach(() => {
  server.close();
});
```
